{{- range .Values.kubearchive.watchNamespaces }}
---
apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: {{ .apiServerSource.name }}
  namespace: {{ .name }}
spec:
  serviceAccountName: {{ $.Values.kubearchive.serviceAccount }}
  mode: {{ .apiServerSource.mode }}
  resources:
    {{- range .apiServerSource.resources }}
    - apiVersion: {{ .apiVersion }}
      kind: {{ .kind }}
    {{- end }}
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: {{ $.Values.sink.name }}
      namespace: {{ $.Values.kubearchive.namespace }}
{{- end }}
