# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
run:
  timeout: 10m
linters:
  enable:
    - bodyclose
    - containedctx
    - fatcontext
    - gofmt
    - gosec
    - nilerr
    - usestdlibvars
    - wastedassign
issues:
  exclude-files:
    - cmd/operator/internal/controller/kubearchiveconfig_controller.go  # errcheck fails on lines 55-58. I tried to fix it but that caused tests to fail. TODO: fix file and remove this line
