# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
extends: default
ignore:
  - charts/kubearchive/
  - charts/generated/kubearchive/charts/
rules:
  line-length: disable
  truthy: disable
