---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: <db_name>    # postgresdb
  POSTGRES_USER: <db_user>   # admin or ps_user
  POSTGRES_PASSWORD: <db_pass>    # a secure password
