# yamllint disable rule:braces
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.database.name }}
  name: {{ .Values.database.name | default "postgresql" }}-volume-claim
  namespace: {{ .Values.kubearchive.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.database.volumes.storage | default "5Gi" }}
