# yamllint disable rule:braces
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.database.name | default "postgresql" }}
  name: {{ .Values.database.name | default "postgresql" }}
  namespace: {{ .Values.kubearchive.namespace }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
  selector:
    app: {{ .Values.database.name | default "postgresql" }}
