# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterkubearchiveconfig-read
  labels:
    app.kubernetes.io/name: "kubearchive-operator"
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
rules:
- apiGroups:
  - kubearchive.kubearchive.org
  resources:
  - clusterkubearchiveconfigs
  verbs:
  - get
  - list
