---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.apiServer.name . }}
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: {{ tpl .Values.apiServer.name . }}
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: {{ tpl .Values.apiServer.name . }}
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ tpl .Values.apiServer.secret . }}
      containers:
        - name: {{ tpl .Values.apiServer.name . }}
          image: {{ .Values.apiServer.image }}
          volumeMounts:
            - name: tls-secret
              readOnly: true
              mountPath: /etc/kubearchive/ssl/
          {{- if .Values.apiServer.debug }}
          command: ["./go/bin/dlv"]
          args: ["--listen=:40000", "--headless=true", "--api-version=2", "--log", "exec", "/ko-app/api"]
          {{- end}}
          env:
{{ include "kubearchive.v1.otel.env" .Values.apiServer | indent 12 }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ tpl .Values.apiServer.name . }}
spec:
  selector:
    app: {{ tpl .Values.apiServer.name . }}
  ports:
    - protocol: TCP
      port: {{ .Values.apiServer.port }}
      targetPort: {{ .Values.apiServer.port }}
