# yamllint disable-file
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.apiServer.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.apiServer.name }}
    namespace: {{ .Values.kubearchive.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.apiServer.name }}
