---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiServer.name }}
---
# Service account that must only be used for development purposes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiServer.testSA }}
